allowNesting: false
packTypes:
    - {material: leather, material_count: 8, size: 45}
    - {material: wool, material_count: 8, size: 27, hasWorkbench: true}
    - {material: string, material_count: 4, size: 9}

