name: Chestpack
main: me.exphc.Chestpack.Chestpack
version: 1.0
commands:
    chestpack:
        description: Open a chestpack
        usage: /<command> id
        aliases: [pack, cp]
permissions:
    chestpack.*:
        children: 
            chestpack.admin: true
        default: false
    chestpack.admin:
        description: Allows you to open any chestpack with the /chestpack command
        default: op

